name: Phase 9 - Legendary Groups (strict)

on:
  pull_request:
    branches: [ master ]
    paths:
      - "schema/2024/v1/rules.legendarygroup.schema.json"
      - "scripts/validate_phase9_legendarygroups.py"
      - "scripts/_validation_common.py"
      - "scripts/__init__.py"
      - "rules/2024/legendaryGroup.json"
      - "rules/2024/legendarygroup.json"
      - ".github/workflows/phase9-legendarygroups.yml"
  push:
    branches-ignore: [ master ]
    paths:
      - "schema/2024/v1/rules.legendarygroup.schema.json"
      - "scripts/validate_phase9_legendarygroups.py"
      - "scripts/_validation_common.py"
      - "scripts/__init__.py"
      - "rules/2024/legendaryGroup.json"
      - "rules/2024/legendarygroup.json"
      - ".github/workflows/phase9-legendarygroups.yml"
  workflow_dispatch:

jobs:
  validate-legendarygroups:
    name: Validate legendary groups (Phase 9 strict)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -VV
          python -m pip install --upgrade pip jsonschema
      - name: Run strict validator (module mode)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m scripts.validate_phase9_legendarygroups
