name: Phase 9 - Status (strict)

on:
  push:
    paths:
      - "schema/2024/v1/rules.status.schema.json"
      - "scripts/validate_phase9_status.py"
      - "scripts/_validation_common.py"
      - "scripts/__init__.py"
      - "rules/2024/status.json"
      - "rules/2024/Status.json"
      - ".github/workflows/phase9-status.yml"
  pull_request:
    paths:
      - "schema/2024/v1/rules.status.schema.json"
      - "scripts/validate_phase9_status.py"
      - "scripts/_validation_common.py"
      - "scripts/__init__.py"
      - "rules/2024/status.json"
      - "rules/2024/Status.json"
      - ".github/workflows/phase9-status.yml"

jobs:
  validate-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip jsonschema
      - name: Validate Status (Phase 9 strict)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m scripts.validate_phase9_status
