name: Phase 9 - Background Fluff (strict)

on:
  push:
    paths:
      - 'schema/2024/v1/rules.backgroundfluff.schema.json'
      - 'scripts/validate_phase9_backgroundfluff.py'
      - 'scripts/_validation_common.py'
      - 'scripts/__init__.py'
      - 'rules/2024/backgroundFluff.json'
      - 'rules/2024/BackgroundFluff.json'
      - '.github/workflows/phase9-backgroundfluff.yml'
      - 'rules/2024/*backgroundfluff*.json'
  pull_request:
    paths:
      - 'schema/2024/v1/rules.backgroundfluff.schema.json'
      - 'scripts/validate_phase9_backgroundfluff.py'
      - 'scripts/_validation_common.py'
      - 'scripts/__init__.py'
      - 'rules/2024/backgroundFluff.json'
      - 'rules/2024/BackgroundFluff.json'
      - '.github/workflows/phase9-backgroundfluff.yml'
      - 'rules/2024/*backgroundfluff*.json'

jobs:
  validate-backgroundfluff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip jsonschema
      - name: Validate Background Fluff (Phase 9 strict)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m scripts.validate_phase9_backgroundfluff
