name: phase9-spell-index-guard
on:
  pull_request:
    paths:
      - "rules/2024/spell.json"
      - "indexes/2024/spells_by_class_level.json"
      - "scripts/**/build_spells_by_class_level.py"
      - ".github/workflows/phase9-spell-index-guard.yml"
  push:
    branches: [ master ]
    paths:
      - "rules/2024/spell.json"
      - "indexes/2024/spells_by_class_level.json"
      - "scripts/**/build_spells_by_class_level.py"
      - ".github/workflows/phase9-spell-index-guard.yml"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
      - name: Guard spells index build
        run: |
          echo "Hook your Phase 9 index guard here"; exit 0
