name: Phase 8 — Spells (strict)

on:
  pull_request:
  push:

jobs:
  phase8-strict:
    name: Validate spells + spells index (strict)
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install jsonschema

      - name: Run Phase 8 strict validator
        run: |
          python scripts/validate_phase8_spells.py
