name: Phase 9 - Actions (strict)

on:
  pull_request:
    branches: [ master ]
    paths:
      - "schema/2024/v1/rules.action.schema.json"
      - "scripts/validate_phase9_actions.py"
      - "scripts/_validation_common.py"
      - "scripts/__init__.py"
      - "rules/2024/action.json"
      - ".github/workflows/phase9-actions.yml"
  push:
    branches-ignore: [ master ]
    paths:
      - "schema/2024/v1/rules.action.schema.json"
      - "scripts/validate_phase9_actions.py"
      - "scripts/_validation_common.py"
      - "scripts/__init__.py"
      - "rules/2024/action.json"
      - ".github/workflows/phase9-actions.yml"
  workflow_dispatch:

jobs:
  validate-actions:
    name: Validate actions (Phase 9 strict)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        # normalised: pinned-runtime
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        uses: - name: Install deps
        uses:   run: |
        uses:     python -m pip install --upgrade pip
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -VV
          python -m pip install --upgrade pip jsonschema
      - name: Run strict validator (module mode)
        run: |
          python -m scripts.validate_phase9_actions






