name: Phase 7 Pilot — strict schema for spells index

on:
  push:
  pull_request:

jobs:
  pilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        # normalised: pinned-runtime
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        uses: - name: Install deps
        uses:   run: |
        uses:     python -m pip install --upgrade pip
        with:
          python-version: "3.11"


      - name: Run Phase 7 strict validator
        run: python scripts/validate_phase7_pilot.py






