name: phase9-objectFluff
on:
  pull_request:
    paths:
      - "rules/2024/objectFluff.json"
      - "schema/2024/v1/objectFluff.schema.json"
      - "scripts/phase9/validate_objectFluff.py"
      - ".github/workflows/phase9-objectFluff.yml"
  push:
    branches: [ master ]
    paths:
      - "rules/2024/objectFluff.json"
      - "schema/2024/v1/objectFluff.schema.json"
      - "scripts/phase9/validate_objectFluff.py"
      - ".github/workflows/phase9-objectFluff.yml"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
      - name: Validate objectFluff.json
        run: |
          python scripts/phase9/validate_objectFluff.py




