name: Schema Validation (warn-only)

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install validator deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Run validator (warn-only)
        run: |
          python scripts/validate_json.py --baseline rules/2024 --indexes indexes/2024 --schemas schema/2024/v0 --reports reports
        continue-on-error: true

      - name: Upload validation log artifact
        uses: actions/upload-artifact@v4
        with:
          name: validation-log
          path: reports/**/validation.log
          if-no-files-found: warn
